### ISSUE TITLE
RtcmV3Parser  bug

### ISSUE THREAD

**Issue by bdfan** [asvol/asv-gnss#1]
RtcmV3Parser.cs    line 85-87

                        var msgNumber = (ushort)BitHelper.GetBitU(_buffer, 24 /* preamble-8bit + reserved-6bit + length-10bit */, 12);
                        var span = new ReadOnlySpan<byte>(_buffer,0,_payloadLength + 3 /* preamble-8bit + reserved-6bit + length-10bit 2022-10-26 by gwy 将6改为3*/ + 3 /*CRC24*/);
                        ParsePacket(msgNumber, ref span,true); // 
                        //return true;//必须注释，否则不执行Reset，解析下一个语句不正确

**Comment by bdfan** [comment]
The RTCM1020 statement parsing is inconsistent with the fields defined in Table 3.5-22

**Comment by asvol** [comment]
Hi! Couldn't find RTK receiver to check RTCMv3 1020 message. Can you check it? (https://github.com/asvol/asv-gnss/tree/1-rtcmv3parser-bug)

**Comment by bdfan** [comment]
var s = "D3 00 2D 3F C1 D9 8B 98 AF 99 B6 26 88 E1 3C 41 20 ED 31 41 83 4D C0 A0 1D 36 4A 95 81 D4 80 0D 05 AD 88 80 18 10 E0 38 00 00 00 11 C0 00 33 80 6D FB 3A D3 00 BA 43 30 00 6E 6C 01 62 00 20 10 00 82 65 80 00 00 00 20 20 00 00 7F FF A6 28 22 25 A3 27 A1 A3 80 00 00 00 3B 27 90 62 CE 66 6D 1F EA 04 82 72 17 A8 03 9E D2 03 EE 0A 27 FA 5F 56 97 8E 32 85 EB 5F E2 97 39 AE 88 7D 23 BA FF 07 4E 11 A3 91 D3 2C C6 2C 3C 6C 7D 1B 3A D2 8B 31 DC 2C CE 38 09 71 A0 29 20 7F 02 DF FC 08 D7 59 A4 1D 89 CE 01 2C 6A 04 BC 57 1F 1A 1F C9 27 F8 B0 E7 E2 CE 0F D4 18 FF 50 DC F7 77 77 77 77 66 77 77 00 00 5D 75 93\r\nE3 8D D5 E5 95 94 65 96 9A 04 7A 08 FC 60 78 C1 E0 CD C1 9B BE 14 3C 26 26 73 4C F0 67 50 CE AD 93 CB 27 D6 AA AD 54 80 CB 03 2B D3 00 6C 43 D0 00 A9 FE E6 22 00 20 03 E0 00 00 00 00 00 00 20 40 00 00 5F C8 48 29 88 08 E7 9A A1 2A 15 57 4C C7 CA FC 68 09 B8 5E 60 05 04 2F A3 2F 9B 6F 3C 2C B4 99 A0 81 21 82 A2 E5 3D E3 A4 77 E6 A3 5F 9A 53 7A 29 85 DA 67 47 AB 0B 7E AC 80 75 20 61 DD DB BD DC 01 56 58 D1 66 59 5B BE 10 BA 31 74 60 80 A1 03 C3 58 06 B1 1A 70 7E A3 EB D3 00 AA 46 50 00 6E 6B 26 A0 00 20 71 20 89 00 00 00 00 00 20 02 00 00 7F FD 3F 3F 3E BF C1 3C 25 26 80 00 00 00 64 CC F0 2C CF 61 95 34 08 42 7F F7 FF FF FF 20 8D 82 12 01 00 20 5F 40 84 26 09 F9 C8 B3 93 96 AE 1D 64 45 40 0A A7 09 05 14 92 09 FC 1D A7 5A 1F E1 9F E7 80 FF 8A 9F E1 D2 FF 87 42 9D 15 61 74 56 FE 2C F1 10 B9 10 00 86 86 02 1C 58 17 A0 38 5E 99 20 80 68 7C 13 1D 77 DD DD DD 55 DD DC 00 05 F5 D7 6D F6 DD 6D 54 E3 7E 59 5C 3E BA BF D8 5B B2 30 05 DF F0 E5 98 8B 4E 14 94 2A 40 21 1C 41 30 C7 2B 2F 60 62 E3 75";

1020 message data

**Comment by asvol** [comment]
Check it.
